"""Add HAMMS v3.0 and AI analysis tables

Revision ID: 415130a9660e
Revises: 
Create Date: 2025-09-09 03:37:09.773888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '415130a9660e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('subgenre', sa.String(length=100), nullable=True),
    sa.Column('mood', sa.String(length=100), nullable=True),
    sa.Column('era', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('openai_response', sa.Text(), nullable=True),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('track_id')
    )
    op.create_table('hamms_advanced',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('vector_12d', sa.Text(), nullable=False),
    sa.Column('dimension_scores', sa.Text(), nullable=True),
    sa.Column('similarity_cache', sa.Text(), nullable=True),
    sa.Column('ml_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('track_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hamms_advanced')
    op.drop_table('ai_analysis')
    # ### end Alembic commands ###
