"""Add ISRC support to tracks and ai_analysis tables

Revision ID: e3cbceee998f
Revises: 415130a9660e
Create Date: 2025-09-09 04:05:43.478686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3cbceee998f'
down_revision: Union[str, Sequence[str], None] = '415130a9660e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analysis', sa.Column('isrc', sa.String(length=15), nullable=True))
    op.add_column('tracks', sa.Column('isrc', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'isrc')
    op.drop_column('ai_analysis', 'isrc')
    # ### end Alembic commands ###
