# MAP4 Default Configuration
# Music Analyzer Pro - Unified Configuration

cli:
  default_provider: "zai"
  output_format: "json"
  verbose: false
  debug: false

providers:
  zai:
    api_key_env: "ZAI_API_KEY"
    base_url: "https://api.zai.com/v1"
    model: "gpt-4"
    timeout: 30
    max_retries: 3
    batch_size: 10
  
  claude:
    api_key_env: "ANTHROPIC_API_KEY"
    model: "claude-3-haiku-20240307"
    timeout: 30
    max_retries: 3
    batch_size: 5
  
  gemini:
    api_key_env: "GEMINI_API_KEY"
    model: "gemini-1.5-flash"
    timeout: 30
    max_retries: 3
    batch_size: 10
  
  openai:
    api_key_env: "OPENAI_API_KEY"
    base_url: "https://api.openai.com/v1"
    model: "gpt-4-turbo-preview"
    timeout: 30
    max_retries: 3
    batch_size: 10

analysis:
  batch_size: 10
  retry_attempts: 3
  cache_results: true
  cache_directory: "data/cache"
  parallel_processing: false
  max_workers: 4

storage:
  database_path: "data/music.db"
  backup_enabled: true
  backup_directory: "data/backups"
  auto_migrate: true

playlist:
  default_format: "m3u"
  default_count: 20
  shuffle_by_default: false
  optimize_flow: true

bmad:
  certification_threshold: 0.95
  validation_strict: true
  report_format: "markdown"
  phases:
    build:
      enabled: true
      threshold: 0.95
    measure:
      enabled: true
      threshold: 0.90
    analyze:
      enabled: true
      threshold: 0.85
    deploy:
      enabled: true
      threshold: 0.95

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/map4.log"
  max_size: "10MB"
  backup_count: 5

export:
  formats:
    - json
    - csv
    - xml
    - yaml
  default_format: "json"
  include_metadata: true
  pretty_print: true